---

# qb machine config.
machine:
  vagrantfile: "machine/vagrant/"

# qb container config.
container:
  lxd_api:
    url:  "https://127.0.0.1:9443"
    cert: "machine/vagrant/lxd/client.crt"
    key:  "machine/vagrant/lxd/client.key"
